name: TestDeploy
on:
  workflow_dispatch:
    inputs:
      md5sum:
        description: 'md5sum Artifact'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy
        run: |
          echo md5:  ${{ github.event.inputs.md5sum }}
          DIA=`date +"%d/%m/%Y"`
          HORA=`date +"%H:%M"`
          echo "$DIA - $HORA"