name: Failure expresion

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
      - name: JobA fail
        run: |
          echo "exit error"
          #exit 1

  job2:
    runs-on: ubuntu-latest
    needs: job1
    
    steps:
      - name: Job con dependencia
        run: echo "Fallo el job1"
        #if: failure()
        #run: echo "Fallo el job1"