name: Job Runs on Failure

on: [push]

jobs:
  main-job:
    runs-on: ubuntu-latest
    allow-failure: true
    steps:
      - name: Fail intentionally
        run: exit 1  # Simulating failure
        continue-on-error: true

  run-on-failure:
    runs-on: ubuntu-latest
    needs: main-job  # Runs after main-job
    if: always()
    if: failure()  # Only runs if main-job fails
    steps:
      - name: Notify on failure
        run: echo "Previous job failed! Running recovery actions..."