name: Job Runs on Failure

on: [push]

jobs:
  main-job:
    runs-on: ubuntu-latest
    #allow-failure: true
    continue-on-error: true
    steps:
      - id: build
      - name: Fail intentionally
        run: exit 1 # Simulating failure

  run-on-failure:
    runs-on: ubuntu-latest
    needs: main-job  # Runs after main-job
    if: failure()  # Only runs if main-job fails
    steps:
      - name: Notify on failure
        run: echo "Previous job failed! Running recovery actions..."