name: Failure expresion

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: JobA fail
        run: exit 1
        continue-on-error: true

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job con dependencia
        if: ${{ failure() }}
        run: echo 'Fallo el job1'