name: Failure expresion

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
      - name: primer job
        run: echo 'primer job'
        
      - name: JobA fail
        continue-on-error: true
        run: exit 1

  job2:
    runs-on: ubuntu-latest
    needs: job1
    
    steps:
      - name: segundo job
        run: echo 'segundo job'
    
      - name: Job con dependencia
        run: echo 'fallo'
        #if: failure()
        #run: echo 'Fallo el job1'