name: Failure expresion jobs

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
      - name: JobA fail
        run: |
          echo "exit error"
          exit 1

  job2:
    needs: job1
    #if: ${{ failure() }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Job con dependencia
        run: echo "Fallo el job1"

  job3:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Job con dependencia
        run: echo "job3"
