name: Job Runs on Failure

on: [push]

jobs:
  main-job:
    runs-on: ubuntu-latest
    allow-failure: true
    steps:
      - id: build
      - name: Fail intentionally
        strategy:
        matrix:
        code: [1]
        run: exit ${{ matrix.code }} # Simulating failure
        continue-on-error: true
      - uses: mainmatter/continue-on-error-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          outcome: ${{ steps.build.outcome }}
          test-id: Error code ${{ matrix.code }}

  run-on-failure:
    runs-on: ubuntu-latest
    needs: main-job  # Runs after main-job
    if: always()
    if: failure()  # Only runs if main-job fails
    steps:
      - name: Notify on failure
        run: echo "Previous job failed! Running recovery actions..."